apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-xresources-merger
spec:
  compositeTypeRef:
    apiVersion: resources-merger.fn.canilho.net/v1alpha1
    kind: xMerger
  mode: Pipeline
  pipeline:
  - step: run
    functionRef:
      name: function-xresources-merger
    input:
      apiVersion: resources-merger.fn.canilho.net/v1alpha1
      kind: Input
      debug: true
      targetRef:
        namespace: ephemeral
        name: merged
        apiVersion: v1
        kind: ConfigMap
      sourceRefs:
        - namespace: ephemeral
          name: map-1
          apiVersion: v1
          kind: ConfigMap
#          extractFromKey: nested
        - namespace: ephemeral
          name: map-2
          apiVersion: v1
          kind: ConfigMap
        - namespace: ephemeral
          name: envcfg-1
          apiVersion: apiextensions.crossplane.io/v1alpha1
          kind: EnvironmentConfig
        - namespace: ephemeral
          name: envcfg-2
          apiVersion: apiextensions.crossplane.io/v1alpha1
          kind: EnvironmentConfig
