apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-resources-merger
spec:
  compositeTypeRef:
    apiVersion: resources-merger.fn.canilho.net/v1alpha1
    kind: XMerger
  mode: Pipeline
  pipeline:
  - step: run
    functionRef:
      name: function-resources-merger
    input:
      apiVersion: merger.fn.canilho.net/v1beta1
      kind: Merge
      debug: true
      mergeStrategy: ForceMergeObjects
      parseEmbedded: true
      target:
        apiVersion: v1
        kind: ConfigMap
        nameFromCompositeFieldPath: spec.appName
        namespace: ephemeral
        context:
          key: myorg.example/merged-config
      sources:
        - name: map-1
          ref:
            apiVersion: v1
            kind: ConfigMap
            namespace: ephemeral
            name: map-1
        - name: map-2
          ref:
            apiVersion: v1
            kind: ConfigMap
            namespace: ephemeral
            name: map-2
        - name: envcfg-1
          ref:
            apiVersion: apiextensions.crossplane.io/v1beta1
            kind: EnvironmentConfig
            name: envcfg-1
        - name: envcfg-2
          toFieldPath: overrides
          ref:
            apiVersion: apiextensions.crossplane.io/v1beta1
            kind: EnvironmentConfig
            name: envcfg-2
