apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xmergers.example.canilho.net
spec:
  scope: Cluster
  group: example.canilho.net
  names:
    kind: XMerger
    plural: xmergers
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appName:
                  type: string
              required:
                - appName
