---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "github.com/crossplane/crossplane-runtime"
        versions: [ "*" ]
      - dependency-name: "github.com/imdario/mergo"
        versions: [ "*" ]
