repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run -c .golangci.yaml --fix
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: go test -v ./...
        language: system
        pass_filenames: false
