---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-resources-merger
  annotations:
#     This tells crossplane composition render to connect to the function locally.
    render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: function-resources-merger
